### ISSUE TITLE
Dialogues: Fly-in letters not working correctly

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#11]
Depending on the key stroke timing the behaviour is different:
![GIF](https://user-images.githubusercontent.com/29095714/112749115-8f8ff080-8fc0-11eb-81e1-cb938d532ffb.gif)

The behaviour should be like the following:
- Player press E -> Dialogue starts with normal fly-in speed

- Player holds down E again -> fly-in speed up (while press -> released)

- Player still holding E from opening -> after a hold timer timeout -> instant display the text
    - Player shall be required to release E and press E again to press the button, maybe remove focus and reclaim focus after all text  ist displayed

**Comment by kneghtmare** [comment]
I don't think I get what you mean but I've made some changes include the timer to the dialog, hope you are happy with that
