### ISSUE TITLE
(Pressure) Buttons can become out of sync 

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#13]
I managed to de-sync button and door. This should not be possible.
In this case the door should be open on standing on the button and it should be closed when walking off.
![GIF](https://user-images.githubusercontent.com/29095714/112749555-4ab98900-8fc3-11eb-8a89-9f852305cac3.gif)

**Comment by themangomago** [comment]
Its simple to re-create this by stepping on/off a plate very quick

**Comment by kneghtmare** [comment]
made some changes in DoorWall.gd, doesn't happen anymore @themangomago
