### ISSUE TITLE
Money resets / strange behaviour

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#14]
What I did:
HQ: looted boss box +20
Completed Mission 1: +100

Entered HQ again with $120. Looted boss box again -> Money = $20
Entered mission 2: Money = $0

**Comment by kneghtmare** [comment]
Hmm I think the money in the level is the money gained in level, not total amount of money, money in HQ is total amount of money @themangomago

**Comment by themangomago** [comment]
fixed it
