### ISSUE TITLE
SimonSays minigame, light broken

### ISSUE THREAD

**Issue by kodkuce** [NimbleBeasts/NbMoonshot#15]
Light on start blinks sometime wrong from what i see
ref video
https://discord.com/channels/584847364318167088/784004640512802826/825686884822679572

**Comment by kneghtmare** [comment]
fixed, check now @kodkuce

**Comment by kodkuce** [comment]
suggestion, would make it unblink before go to next lite cuz when it blinks 2 times in a row same light if no sound you dont know

**Comment by themangomago** [comment]
added real light2d nodes
