### ISSUE TITLE
Cannot drop items if text message appears

### ISSUE THREAD

**Issue by Keldorem** [NimbleBeasts/NbMoonshot#34]
If I have picked up an item and enter an area where a message appears, e.g. in the intro level, then I can't drop the item anymore.

**Comment by kneghtmare** [comment]
Sorry for the late response, but I can't reproduce this

**Comment by kneghtmare** [comment]
Thanks for the report, I was able to reproduce this

**Comment by themangomago** [comment]
fixed for HQ level
