### ISSUE TITLE
Minigames wont open again after Ingame Menu opened and closed

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#37]
Got this issue with metal door lockpicking. I wanted to cancel it so I hit ESC resulting in opening the menu. Continuing wont let me open the minigame again.
Guess best to do here is to not opening the menu if a minigame is opened, but quitting the minigame instead.

**Comment by themangomago** [comment]
It looks like that if you fail a minigame you cant even enter minigame anymore. 
E.g. Level6 frontdoor

**Comment by kneghtmare** [comment]
fixed @themangomago
