### ISSUE TITLE
Guards walking thru closed doors

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#38]
Guards are walking thru closed doors. When the door is not locked they open it.

Guards with attribute set "canOpenClosedDoors" shall be able to open the, even if lock level 1 or 2.
If they are locked not on level1 or level2 they shall OR the guard dont have canOpenClosedDoors set to false, they shall return.

**Comment by kneghtmare** [comment]
added @themangomago

**Comment by themangomago** [comment]
fixed
