### ISSUE TITLE
Lockpicking become incredibly hard

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#6]
![GIF](https://user-images.githubusercontent.com/29095714/112457488-1d1ed680-8d5c-11eb-83e6-275a3e7d9418.gif)
Dont know what happend but the lockpicking is ultra hard :D

**Comment by kneghtmare** [comment]
actually don't know how it happens. maybe @kodkuce knows?

**Comment by themangomago** [comment]
needs to be re-validated on my high end machine.
