### ISSUE TITLE
Carried item stuck

### ISSUE THREAD

**Issue by themangomago** [NimbleBeasts/NbMoonshot#8]
When walking with a carried item over a pressure plate, you cannot drop the item afterwards.

**Comment by kneghtmare** [comment]
![image](https://user-images.githubusercontent.com/72059398/112966249-ad4b8a00-9167-11eb-9f18-039a33818773.png)
wdym?

**Comment by kneghtmare** [comment]
![umm](https://user-images.githubusercontent.com/72059398/112966425-db30ce80-9167-11eb-883c-58843aabbbe1.gif)
It's working for me unless I misunderstood the issue @themangomago

**Comment by themangomago** [comment]
was not able to recreate
